---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: ['--ignore', 'D100,D104,D200,D400,D401,D402,D403,E501,E402,E722,E712,W504', 'openbbs_middleware']
        exclude: (^tests|^.cc)
        additional_dependencies:
          - flake8-absolute-import
          - flake8-docstrings
