# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
      - python: 3.7
        env: TOXENV=lint
      - python: 3.7
        env: TOXENV=py37
      - python: 3.8
        env: TOXENV=py38

script: tox

install:
    - pip install tox

after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - pip install codecov
    - codecov -e TOXENV TRAVIS_OS_NAME
